import type { Metadata } from "next";
import "../assets/scss/globals.scss";
import { getGlobalPageData, getGlobalPageMetadata } from "@/data/loader";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
    const metadata = await getGlobalPageMetadata();

    return {
        title: metadata.data.title,
        description: metadata.data.description,
    }
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const globalData = await getGlobalPageData();

    return (
        <html lang="en">
            <body className=''>
                <Header data={globalData.data.header} />
                {children}
                <Footer data={globalData.data.footer} />
            </body>
        </html>
    );
}
